name: CI/CD Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Check out repository
        uses: actions/checkout@v4

      - name: 🛠 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: 🔒 Configure Shopify CLI
        run: |
          echo "store: ${{ secrets.SHOPIFY_STORE }}" >> ~/.shopify-cli.yml
          echo "password: ${{ secrets.SHOPIFY_PASSWORD }}" >> ~/.shopify-cli.yml
          echo "theme_id: ${{ secrets.SHOPIFY_THEME_ID }}" >> ~/.shopify-cli.yml

      - name: 🚀 Deploy theme to Shopify
        run: shopify theme push --allow-live --theme ${{ secrets.SHOPIFY_THEME_ID }}
